# Generated by Django 4.1 on 2024-09-16 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0003_alter_comment_posted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="caption",
        ),
    ]
