# Generated by Django 4.1 on 2024-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0004_remove_post_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(max_length=100),
        ),
    ]
